// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: proto/getSession.proto

package getSession

import (
	fmt "fmt"
	proto "google.golang.org/protobuf/proto"
	math "math"
)

import (
	context "context"
	api "go-micro.dev/v4/api"
	client "go-micro.dev/v4/client"
	server "go-micro.dev/v4/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// Reference imports to suppress errors if they are not otherwise used.
var _ api.Endpoint
var _ context.Context
var _ client.Option
var _ server.Option

// Api Endpoints for GetSession service

func NewGetSessionEndpoints() []*api.Endpoint {
	return []*api.Endpoint{}
}

// Client API for GetSession service

type GetSessionService interface {
	Call(ctx context.Context, in *CallRequest, opts ...client.CallOption) (*CallResponse, error)
	ClientStream(ctx context.Context, opts ...client.CallOption) (GetSession_ClientStreamService, error)
	ServerStream(ctx context.Context, in *ServerStreamRequest, opts ...client.CallOption) (GetSession_ServerStreamService, error)
	BidiStream(ctx context.Context, opts ...client.CallOption) (GetSession_BidiStreamService, error)
}

type getSessionService struct {
	c    client.Client
	name string
}

func NewGetSessionService(name string, c client.Client) GetSessionService {
	return &getSessionService{
		c:    c,
		name: name,
	}
}

func (c *getSessionService) Call(ctx context.Context, in *CallRequest, opts ...client.CallOption) (*CallResponse, error) {
	req := c.c.NewRequest(c.name, "GetSession.Call", in)
	out := new(CallResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *getSessionService) ClientStream(ctx context.Context, opts ...client.CallOption) (GetSession_ClientStreamService, error) {
	req := c.c.NewRequest(c.name, "GetSession.ClientStream", &ClientStreamRequest{})
	stream, err := c.c.Stream(ctx, req, opts...)
	if err != nil {
		return nil, err
	}
	return &getSessionServiceClientStream{stream}, nil
}

type GetSession_ClientStreamService interface {
	Context() context.Context
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	CloseSend() error
	Close() error
	Send(*ClientStreamRequest) error
}

type getSessionServiceClientStream struct {
	stream client.Stream
}

func (x *getSessionServiceClientStream) CloseSend() error {
	return x.stream.CloseSend()
}

func (x *getSessionServiceClientStream) Close() error {
	return x.stream.Close()
}

func (x *getSessionServiceClientStream) Context() context.Context {
	return x.stream.Context()
}

func (x *getSessionServiceClientStream) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *getSessionServiceClientStream) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *getSessionServiceClientStream) Send(m *ClientStreamRequest) error {
	return x.stream.Send(m)
}

func (c *getSessionService) ServerStream(ctx context.Context, in *ServerStreamRequest, opts ...client.CallOption) (GetSession_ServerStreamService, error) {
	req := c.c.NewRequest(c.name, "GetSession.ServerStream", &ServerStreamRequest{})
	stream, err := c.c.Stream(ctx, req, opts...)
	if err != nil {
		return nil, err
	}
	if err := stream.Send(in); err != nil {
		return nil, err
	}
	return &getSessionServiceServerStream{stream}, nil
}

type GetSession_ServerStreamService interface {
	Context() context.Context
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	CloseSend() error
	Close() error
	Recv() (*ServerStreamResponse, error)
}

type getSessionServiceServerStream struct {
	stream client.Stream
}

func (x *getSessionServiceServerStream) CloseSend() error {
	return x.stream.CloseSend()
}

func (x *getSessionServiceServerStream) Close() error {
	return x.stream.Close()
}

func (x *getSessionServiceServerStream) Context() context.Context {
	return x.stream.Context()
}

func (x *getSessionServiceServerStream) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *getSessionServiceServerStream) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *getSessionServiceServerStream) Recv() (*ServerStreamResponse, error) {
	m := new(ServerStreamResponse)
	err := x.stream.Recv(m)
	if err != nil {
		return nil, err
	}
	return m, nil
}

func (c *getSessionService) BidiStream(ctx context.Context, opts ...client.CallOption) (GetSession_BidiStreamService, error) {
	req := c.c.NewRequest(c.name, "GetSession.BidiStream", &BidiStreamRequest{})
	stream, err := c.c.Stream(ctx, req, opts...)
	if err != nil {
		return nil, err
	}
	return &getSessionServiceBidiStream{stream}, nil
}

type GetSession_BidiStreamService interface {
	Context() context.Context
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	CloseSend() error
	Close() error
	Send(*BidiStreamRequest) error
	Recv() (*BidiStreamResponse, error)
}

type getSessionServiceBidiStream struct {
	stream client.Stream
}

func (x *getSessionServiceBidiStream) CloseSend() error {
	return x.stream.CloseSend()
}

func (x *getSessionServiceBidiStream) Close() error {
	return x.stream.Close()
}

func (x *getSessionServiceBidiStream) Context() context.Context {
	return x.stream.Context()
}

func (x *getSessionServiceBidiStream) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *getSessionServiceBidiStream) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *getSessionServiceBidiStream) Send(m *BidiStreamRequest) error {
	return x.stream.Send(m)
}

func (x *getSessionServiceBidiStream) Recv() (*BidiStreamResponse, error) {
	m := new(BidiStreamResponse)
	err := x.stream.Recv(m)
	if err != nil {
		return nil, err
	}
	return m, nil
}

// Server API for GetSession service

type GetSessionHandler interface {
	Call(context.Context, *CallRequest, *CallResponse) error
	ClientStream(context.Context, GetSession_ClientStreamStream) error
	ServerStream(context.Context, *ServerStreamRequest, GetSession_ServerStreamStream) error
	BidiStream(context.Context, GetSession_BidiStreamStream) error
}

func RegisterGetSessionHandler(s server.Server, hdlr GetSessionHandler, opts ...server.HandlerOption) error {
	type getSession interface {
		Call(ctx context.Context, in *CallRequest, out *CallResponse) error
		ClientStream(ctx context.Context, stream server.Stream) error
		ServerStream(ctx context.Context, stream server.Stream) error
		BidiStream(ctx context.Context, stream server.Stream) error
	}
	type GetSession struct {
		getSession
	}
	h := &getSessionHandler{hdlr}
	return s.Handle(s.NewHandler(&GetSession{h}, opts...))
}

type getSessionHandler struct {
	GetSessionHandler
}

func (h *getSessionHandler) Call(ctx context.Context, in *CallRequest, out *CallResponse) error {
	return h.GetSessionHandler.Call(ctx, in, out)
}

func (h *getSessionHandler) ClientStream(ctx context.Context, stream server.Stream) error {
	return h.GetSessionHandler.ClientStream(ctx, &getSessionClientStreamStream{stream})
}

type GetSession_ClientStreamStream interface {
	Context() context.Context
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Recv() (*ClientStreamRequest, error)
}

type getSessionClientStreamStream struct {
	stream server.Stream
}

func (x *getSessionClientStreamStream) Close() error {
	return x.stream.Close()
}

func (x *getSessionClientStreamStream) Context() context.Context {
	return x.stream.Context()
}

func (x *getSessionClientStreamStream) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *getSessionClientStreamStream) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *getSessionClientStreamStream) Recv() (*ClientStreamRequest, error) {
	m := new(ClientStreamRequest)
	if err := x.stream.Recv(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (h *getSessionHandler) ServerStream(ctx context.Context, stream server.Stream) error {
	m := new(ServerStreamRequest)
	if err := stream.Recv(m); err != nil {
		return err
	}
	return h.GetSessionHandler.ServerStream(ctx, m, &getSessionServerStreamStream{stream})
}

type GetSession_ServerStreamStream interface {
	Context() context.Context
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Send(*ServerStreamResponse) error
}

type getSessionServerStreamStream struct {
	stream server.Stream
}

func (x *getSessionServerStreamStream) Close() error {
	return x.stream.Close()
}

func (x *getSessionServerStreamStream) Context() context.Context {
	return x.stream.Context()
}

func (x *getSessionServerStreamStream) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *getSessionServerStreamStream) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *getSessionServerStreamStream) Send(m *ServerStreamResponse) error {
	return x.stream.Send(m)
}

func (h *getSessionHandler) BidiStream(ctx context.Context, stream server.Stream) error {
	return h.GetSessionHandler.BidiStream(ctx, &getSessionBidiStreamStream{stream})
}

type GetSession_BidiStreamStream interface {
	Context() context.Context
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Send(*BidiStreamResponse) error
	Recv() (*BidiStreamRequest, error)
}

type getSessionBidiStreamStream struct {
	stream server.Stream
}

func (x *getSessionBidiStreamStream) Close() error {
	return x.stream.Close()
}

func (x *getSessionBidiStreamStream) Context() context.Context {
	return x.stream.Context()
}

func (x *getSessionBidiStreamStream) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *getSessionBidiStreamStream) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *getSessionBidiStreamStream) Send(m *BidiStreamResponse) error {
	return x.stream.Send(m)
}

func (x *getSessionBidiStreamStream) Recv() (*BidiStreamRequest, error) {
	m := new(BidiStreamRequest)
	if err := x.stream.Recv(m); err != nil {
		return nil, err
	}
	return m, nil
}
